name: ci
on: [push, pull_request]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/Andful/pipelined-math:master
    steps:
      - uses: actions/checkout@v2
      - name: Build Testbenches
        run: |
          make
      - name: Run Tests
        run: |
          ls sim/* | xargs -n1 vvp
